// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod tests {
  use super::*;
  pub mod request_reply {
    use super::*;
    mod message_generated;
    pub use self::message_generated::*;
  } // request_reply
} // tests
