//! Request/reply guest module used by the end-to-end test harness.

use anyhow::{Context, Result, anyhow, bail};
use futures::{SinkExt, StreamExt, TryStreamExt};
use selium_atlas::{Atlas, Uri};
use selium_switchboard::{Client, Server, Switchboard};
use selium_userland::{entrypoint, schema};
use tracing::info;

/// Flatbuffer bindings generated by the build script.
#[rustfmt::skip]
#[allow(warnings)]
pub mod fbs;

/// Response payload returned to the request/reply client.
#[schema(
    path = "schemas/message.fbs",
    ty = "tests.request_reply.Message",
    binding = "crate::fbs::tests::request_reply::Message"
)]
pub struct Message {
    /// Echoed payload.
    pub msg: String,
}

#[entrypoint]
async fn request_reply_client(
    ctx: selium_userland::Context,
    control_channel: i32,
    reply_channel: i32,
) -> Result<()> {
    let control_channel = channel_from_arg(control_channel)?;
    let reply_channel = channel_from_arg(reply_channel)?;
    let mut control_subscriber = control_channel.subscribe(32 * 1024).await?;
    match control_subscriber.next().await {
        Some(Ok(_)) => {}
        Some(Err(err)) => return Err(err).context("read control signal"),
        None => bail!("control channel closed before signal"),
    }

    let switchboard = ctx.require::<Switchboard>().await;
    let atlas = ctx.require::<Atlas>().await;

    let server_channel = atlas
        .get(&Uri::parse("sel://moo/cow").unwrap())
        .await?
        .unwrap() as u32;

    let mut client = Client::create(&switchboard).await?;
    client.connect(&switchboard, server_channel).await?;

    let msg = Message::new("ping".to_string());
    info!(request_channel = server_channel, "sending ping");

    let reply: Message = client.request(msg).await?;
    let reply_msg = reply.msg;
    publish_reply(&reply_channel, &reply_msg).await?;

    Ok(())
}

#[entrypoint]
async fn request_reply_server(ctx: selium_userland::Context) -> Result<()> {
    let switchboard = ctx.require::<Switchboard>().await;
    let atlas = ctx.require::<Atlas>().await;

    let server: Server<Message, Message> = Server::create(&switchboard).await?;
    atlas
        .insert(
            Uri::parse("sel://moo/cow").unwrap(),
            server.endpoint_id() as u64,
        )
        .await?;
    server
        .try_for_each(async |req| {
            info!(msg = req.request().msg, "received request");

            req.reply(Message { msg: "pong".into() }).await
        })
        .await?;

    Ok(())
}

fn channel_from_arg(handle: i32) -> Result<selium_userland::io::Channel> {
    let handle = u64::try_from(handle).map_err(|_| anyhow!("channel handle is negative"))?;
    Ok(unsafe { selium_userland::io::Channel::from_raw(handle) })
}

async fn publish_reply(channel: &selium_userland::io::Channel, reply_msg: &str) -> Result<()> {
    let mut publisher = channel.publish().await?;
    publisher.send(reply_msg.as_bytes().to_vec()).await?;
    publisher.close().await?;
    Ok(())
}
